name: workflow
on: [push, workflow_dispatch, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Lint with Black
        run: black .
      - name: Check linting
        uses: psf/black@stable

